### ISSUE TITLE
any course to recommend ?

### ISSUE THREAD

**Issue by snowden-fu** [YUbuntu0109/Python-learning#1]

**Comment by GoogTech** [comment]
❤️ Interest seems ... to be the most ... important thing ~

**Comment by snowden-fu** [comment]
i mean have you got any good course or book to share with us, you can write it in README

**Comment by YUbuntu0109** [comment]
ok

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GoogTech** [comment]
🙂 ok
